### ISSUE TITLE
When a user calls ;waifu with an invalid waifu in their list, a crash occurs. 

### ISSUE THREAD

**Issue by chaosking121** [chaosking121/mal#7]
Example trace:

```
Traceback (most recent call last):
  File "/root/mal_refactor/mal.py", line 114, in <module>
    response = control(slackMessage)
  File "/root/mal_refactor/mal.py", line 25, in control
    return getattr(plugins, command)(slackMessage)
  File "/root/mal_refactor/plugins.py", line 33, in waifu
    return tools.waifu.parseWaifuMessage(slackMessage)
  File "/root/mal_refactor/tools/waifu.py", line 135, in parseWaifuMessage
    selectedImagePath = pickImage(bestGirl)
  File "/root/mal_refactor/tools/waifu.py", line 44, in pickImage
    return dbt.getImage(bestGirl, imageNumber).getPath()
  File "/root/mal_refactor/tools/database_tools.py", line 301, in getImage
    imageNumber = random.randint(1, count)
  File "/usr/lib/python2.7/random.py", line 240, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 216, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, isto$
ValueError: empty range for randrange() (1,1, 0)

```

**Comment by chaosking121** [comment]
I probably should fix this, but it was only a problem because validation of waifu lists wasn't working. So now that I fixed that, this probably shouldn't come up again.

**Comment by chaosking121** [comment]
Guess I'll close it? I think it may actually not be a problem any more with the updated waifu handling stuff for lists and the use of a default waifu.
